services:
  - type: web
    name: luxestay-backend
    env: docker
    plan: free
    rootDir: hotel
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: 8082
